### ISSUE TITLE
Question: can @file:Include be declared in an included file?

### ISSUE THREAD

**Issue by oshai** [holgerbrandl/kscript#149]
My utils.kt start getting big and I thought about splitting it.
I am not sure if that is possible and how (I used this util from couple of scripts)
is the @file:Include can be in the utils.kt itself? What about cyclic dependencies, will that work?

Or maybe I should move to develop a module and use it instead?

**Comment by oshai** [comment]
I think modules suggestion also related to #127

**Comment by holgerbrandl** [comment]
I guess so, see https://github.com/holgerbrandl/kscript/blob/018c63a62e14a3afb4a66f18019756540f2ba448/src/
main/kotlin/kscript/app/ResolveIncludes.kt#L30

If it does not work, could you maybe submit a unit-test/example as a PR. We don't test it at all currently (see https://github.com/holgerbrandl/kscript/blob/ca8668963e319f55c15b62c67a759eafdbf05235/test/test_suite.sh#L247)

See also https://github.com/holgerbrandl/kscript/pull/133

**Comment by holgerbrandl** [comment]
Yes relative paths should be resolved using the including script as "baseline" directory. 

So if the kscriptlet is including `utils/foo.kts` and `foo.kts` is including `./bar.kts`, the latter is expected to be sitting under `utils`. I'd think that the tests cover this to a certain extent already.


I commented on the PR, but once we clarified it, we can merge it in.

**Comment by oshai** [comment]
Thanks, I don't see any comment on the PR for some reason.

**Comment by holgerbrandl** [comment]
See directly under https://github.com/holgerbrandl/kscript/pull/151
I've tried to used the code review feature of github, but maybe not correctly.

**Comment by oshai** [comment]
Maybe you didn't submit it, because I still don't see comment there.

**Comment by holgerbrandl** [comment]
So true. Now it should be better.
